name: lyrics-analysis-env
channels:
  - defaults
dependencies:
  - python=3.11
  - pandas>=1.3.0
  - numpy>=1.21.0
  - matplotlib>=3.4.3
  - seaborn>=0.11.2
  - wordcloud>=1.8.1
  - nltk>=3.6.3
  - vaderSentiment>=3.3.2
  - lyricsgenius>=3.0.1
  - pip
